enum testLocaleKeys {
    STRING_EXIST_KEY_ALL = 'STRING.KEY_FROM_ENUM.EXIST_IN_ALL_LOCALES',
    STRING_EXIST_KEY_ONSE = 'STRING.KEY_FROM_ENUM.EXIST_IN_ONE_LOCALE',
    STRING_ABSENT_KEY_ALL = 'STRING.KEY_FROM_ENUM.ABSENT_IN_ALL_LOCALES', // TODO: RL: Try to find it
    OBJECT_EXIST_KEY_ALL = 'OBJECT.KEY_FROM_ENUM.EXIST_IN_ALL_LOCALES',
}
